### ISSUE TITLE
I'm getting a few errors with qUINT_bloom

### ISSUE THREAD

**Issue by ArkfrostLumas** [Lifell/Stormshade-Testlab#1]
When loading Stormshade I get this error in the statistics

..\qUINT_bloom.fx(131, 44): error X3011: 'BloomTex7_LowestMip': initial value must be a literal expression
..\qUINT_bloom.fx(140, 101): error X3538: 'BloomTex7_LowestMip': initial value must be a literal scalar expression

And on the home page it says "failed to compile"

**Comment by Lifell** [comment]
If you're using the new 4.0.x version then make sure to update the shaders to the latest. I go do that now actually for this depos.

**Comment by ArkfrostLumas** [comment]
Hmmm... Weird. I thought I did that. Did it again and now it's working. Thanks :)

**Comment by Lifell** [comment]
You probably did then :P. I think the shaders weren't updated 2 days ago that's why it didn't work and wouldn't have worked until Marty would update.

I guess he did :].
